### ISSUE TITLE
Tiny Mob Farm - Crash

### ISSUE THREAD

**Issue by SpikedKarma** [DAQEM/TinyMobFarmRemastered#11]
When creating a mob farm in game, clicking on the item to get it to open to enter the lasso - the game crashes. 

As of right now - the tiny mob farms looks to be pointing to using UI LIB 0.3.1 vs UI LIB 0.3.4 - and I am wondering if that is what is causing it to bug out and crash

[crash-2024-04-28_15.23.24-client.-.Tiny.Mob.Farms.txt](https://github.com/DAQEM/TinyMobFarmRemastered/files/15189368/crash-2024-04-28_15.23.24-client.-.Tiny.Mob.Farms.txt)

This looks like it may be related to the UI Lib, but I am not entirely sure, as coding is not my thing.  

I made sure that I swapped 0.3.4 out with the outdated 0.3.1 version of UI LIB - and then the original error above (Game crashing when clicking on the mob farm) happened.

![Screenshot 2024-05-02 084640](https://github.com/DAQEM/TinyMobFarmRemastered/assets/24304683/3e18f68a-357d-430f-b8e9-3b00e07c728d)

**Comment by Tree1568** [comment]
I had this exact issue today in 1.20.1. I gave up trying to open it and destroyed it with a pickaxe, finding that other objects (in my case pumpkins from botany pots) had glitched into it.

**Comment by DAQEM** [comment]
MC Version 1.20.4 is not supported.
