### ISSUE TITLE
No farms in the Game. 

### ISSUE THREAD

**Issue by Maxi90909** [DAQEM/TinyMobFarmRemastered#13]
I installed the mod. I only have the Lasso. Where are the farms?
I don't know what is causing it.

![Screenshot (12)](https://github.com/DAQEM/TinyMobFarmRemastered/assets/76815835/5aae9ef3-a856-4d4d-9ba6-403b6185dfd8)

![Screenshot (13)](https://github.com/DAQEM/TinyMobFarmRemastered/assets/76815835/fd839fe3-a53c-4a9e-b289-571279eb49c0)

**Comment by Maxi90909** [comment]
![Uploading Screenshot (14).png…]()

**Comment by Maxi90909** [comment]
![Screenshot (14)](https://github.com/DAQEM/TinyMobFarmRemastered/assets/76815835/ad1e266a-5632-4362-8a02-ca2dab695cb8)

**Comment by Maxi90909** [comment]
![Screenshot (15)](https://github.com/DAQEM/TinyMobFarmRemastered/assets/76815835/17a7fda7-3889-4164-8d54-c776fde14b14)
Farms don't even exist. Can't craft them. Can't find them in Jei and Creative. hey simply aren't in the game

**Comment by Chasecraft01** [comment]
did you ever find a fix to this? im having this issue in 1.20.1 right now

**Comment by 3th3** [comment]
Still like this ~

**Comment by kezmodius** [comment]
This is also my issue. Hopefully DAQEM can fix it soon.

**Comment by DAQEM** [comment]
Fixed in version 1.3. Sorry for the delay in getting this resolved.
