### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Merithor** [DAQEM/TinyMobFarmRemastered#14]
v1.21-1.20.1 , Fabric.
Modpack: LostCrafter's personal Pack (Have to talk to Traverse Joe, Leialoha, or any of the server Operators to know more, https://www.lostcrafterssmp.com/ )

Bugs:
Certain mobs don't drop anything, despite the timer going down for it. Slimes are an example.
Looting Enchant on Lasso Config turned on does nothing, lassos cannot be enchanted with it.

**Comment by DAQEM** [comment]
Only small slimes drop slime balls and you should be able to put looting on a lasso with a book and an anvil.

**Comment by PalanixYT** [comment]
On Fabric 1.5-1.21 Minecraft Version 1.21.1 it is not possible to enchant the Lasso with Looting (allowLassoLooting: true).
Forcibly enchanting the lasso in Creative Mode doesn't change the drops.
