### ISSUE TITLE
Lasso generates blank label items when capturing Boss Mobs

### ISSUE THREAD

**Issue by Kerrybuck-17** [DAQEM/TinyMobFarmRemastered#18]
For example, to capture Wither

**Comment by DAQEM** [comment]
When you tried to capture a Wither, you should see the error: "Cannot Capture Boss Mobs."

**Comment by Kerrybuck-17** [comment]
> When you tried to capture a Wither, you should see the error: "Cannot Capture Boss Mobs."

lasso still changes state, but the label is blank
