### ISSUE TITLE
Lasso that captures creatures with multiple forms cannot produce items

### ISSUE THREAD

**Issue by Kerrybuck-17** [DAQEM/TinyMobFarmRemastered#19]
Take Slime, for example

**Comment by DAQEM** [comment]
Only small slimes drop slimes. That is how the game works.

**Comment by Kerrybuck-17** [comment]
But I caught the smallest Slime

**Comment by Kerrybuck-17** [comment]
> 只有小史莱姆才会掉落史莱姆。游戏就是这样运作的。

But the one I captured was the smallest Slime, and it still didn't work

**Comment by Kerrybuck-17** [comment]
> 只有小史莱姆才会收集史莱姆。游戏就是这样兼容的。

But the one I captured was the smallest Slime, and it still didn't work

**Comment by DAQEM** [comment]
You are right. they changed the slime loot table when the frog was added.
