### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by aTastyWaifu** [DAQEM/TinyMobFarmRemastered#3]
Anytime I want to try to interact with the mob farm, it crashes the game instantly.

This is what I get;

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void com.daqem.tinymobfarm.client.gui.MobFarmScreen.method_25420(net.minecraft.class_332)'

I'm on fabric 1.20.4

**Comment by DAQEM** [comment]
Only version 1.20.4 is supported at the moment.
