### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by PigeonGod1** [DAQEM/TinyMobFarmRemastered#7]
1.20.1 Fabric Version Bug Report For Tiny Mob Farms

Drop Issues
*Rabbits: dont drop rabbit feet
*blazes dont drop blaze rods
*slimes dont drop slimeballs
*cave spiders dont drop spider eyes
*donkeys cant be picked up with lasso
*drowned dont drop copper ingots
*elder guardians dont drop sponges or random fish
*evokers dont drop emeralds
*horses cant be picked up with lasso
*llamas cant be picked up with lasso
*magma cubes dont drop magma cream
*mules cant be picked up with lasso
*phantoms dont drop phantom membranes
*piglin brutes dont drop golden axes (probably doesnt matter though)
*pillagers dont drop crossbow (probably doesnt matter though)
*skeletons dont drop bows (probably doesnt matter though)
*husks dont drop iron ingots, carrots, and potatoes
*slimes dont drop slimeballs
*spiders dont drop spider eyes
*strays dont drop arrows of slowness or their bow (bow doesnt really matter)
*vindicators dont drop emeralds or their axe (axe doesnt really matter)
*wandering traders cant be picked up
*wither skeletons dont drop wither skeleton skulls
*zombified piglins dont drop gold ingots or their sword (sword doesnt really matter)
*zombies dont drop iron ingots, carrots, and potoes

Bugs
*damaged mobs that are picked up glow red (such as guardians out of water)
*if mobs are on fire when picked up with the lasso it stays
*all farms (except the wooden one) are not easily breakable and they drop nothing after destroyed
*hoppers underneath mob farms take out the lasso instead of the loot

Side Notes:
*elder guardians drops are automatically compatible with the mod "end remastered" (not an issue)
*evoker drops are automatically compatible with the mod "end remastered" (not an issue)
*witches are automatically compatible with the mod "end remastered" (not an issue)

**Comment by DAQEM** [comment]
All issues have been fixed.
